<?php
namespace backend\widgets;

use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

class GroupActionWidge extends Widget
{
    const BUTTON_CLASS = 'btn-group-action';

    public $className;
    public $delete;
    public $activate;
    public $deactivate;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $url = Url::to(['/site/group']);

        if($this->delete) {
            $this->delete();
        }
        if($this->activate) {
            $this->activate();
        }
        if($this->deactivate) {
            $this->deactivate();
        }
        $this->view->registerJs('
   
            $(".'.self::BUTTON_CLASS.'").on("click", function() {
                var action = $(this).attr("value"),
                ids = [],
                className = "'.quotemeta($this->className).'",
                url = "'.$url.'";
              
                $(".grid-view input[type=checkbox]:checked").each(function(index) {
                        ids[index] = $(this).val();
                });
                if (ids.length == 0) {
                    alert("Ничего не выбрано");
                    return ;
                }
             
                var data = {
                    action:action,
                    className: className,
                    ids : ids
                };
                
                 $.ajax({
                       method: "POST",
                       url: url,
                       data: {data:data},
                       dataType: "json",
                       success: function (data) {
                           if (data.status) {
                                  toastr[\'success\'](data[\'message\']);
                                 $.pjax.reload({container:"#content-list"});
                           }
                       }
                   });
            })
        ',View::POS_READY);
    }

    public function delete()
    {
        echo Html::button('<i class="fa fa-trash-o"></i> Удалить', ['value' => 'delete', 'class' => 'btn btn-danger '.self::BUTTON_CLASS]);
    }

    public function activate()
    {
        echo Html::button('<i class="fa fa-toggle-on"></i>  Активировать', ['value' => 'activate', 'class' => 'btn btn-success '.self::BUTTON_CLASS]);
    }

    public function deactivate()
    {
        echo Html::button('<i class="fa fa-toggle-off"></i> Деактивировать', ['value' => 'deactivate', 'class' => 'btn btn-success '.self::BUTTON_CLASS]);
    }
}