<?php

namespace backend\modules\custom_form\models;

use common\models\BaseDataModel;
use yii\helpers\ArrayHelper;

class Form extends BaseDataModel
{
    const TYPE_TEXT = 1;
    const TYPE_PHONE = 2;
    const TYPE_EMAIL = 3;
    const TYPE_AREA = 4;
    const TYPE_SELECT = 5;
    const TYPE_CHECKBOX = 6;
    const TYPE_FILE = 7;

    const ADDITIONAL_DATA_ITEMS = 'items';

    static $current = null;

    public static function tableName()
    {
        return 'custom_form';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_merge(parent::rules(), [
            [['title', 'button', 'email'], 'string', 'max' => 255],
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), [
            'title' => 'Заголовок',
        ]);
    }


    static public function getTypeList()
    {
        return [
            self::TYPE_TEXT => 'text',
            self::TYPE_PHONE => 'phone',
            self::TYPE_EMAIL => 'email',
            self::TYPE_AREA => 'textarea',
            self::TYPE_SELECT => 'select',
            self::TYPE_CHECKBOX => 'checkbox',
            self::TYPE_FILE => 'file',
        ];
    }

    static public function getFormAll($map = false)
    {
        $query = self::find()->where(['status' => self::STATUS_ACTIVE]);

        $models = $query->all();
        if ($map) {
            return [false => 'Выберите форму'] + ArrayHelper::map($models, 'id', 'title');
        }
        return $models;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
