<?php
namespace backend\components;

use yii\base\Action;
use yii\web\Response;

class GroupAction extends Action
{
    public $className;
    public $action;
    public $ids;

    public function init()
    {
        $post = \Yii::$app->request->post('data');
        $this->className = $post['className'];
        $this->action = $post['action'];
        $this->ids = $post['ids'];

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $result = [];

        $class = $this->className;
        $ids = $this->ids;

        foreach ($ids as $id) {
            if ($model = $class::findOne($id)) {
                switch ($this->action) {
                    case 'delete':
                        $result = $this->delete($model);
                        break;
                    case 'activate':
                        $result = $this->activate($model);
                        break;
                    case 'deactivate':
                        $result = $this->deactivate($model);
                        break;
                }
            }
        }

        \Yii::$app->response->format = Response::FORMAT_JSON;

        return ['status' => true, 'message' => 'Действие прошло успешно'];
    }

    public function delete($model)
    {
        $model->delete();
    }

    public function activate($model)
    {
        $model->status = $model::STATUS_ACTIVE;
        $model->save();
    }

    public function deactivate($model)
    {
        $model->status = $model::STATUS_NOTACTIVE;
        $model->save();
    }
}